# Generated by Django 4.2 on 2023-04-05 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created')),
                ('keyword', models.CharField(max_length=254, verbose_name='Keyword')),
                ('date_filter', models.CharField(blank=True, choices=[('', 'None'), ('d1', 'Past 24 Hour'), ('d7', 'Past Week'), ('m1', 'Past Month'), ('y1', 'Past Year')], max_length=4, null=True, verbose_name='Date Filter')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Request User')),
            ],
            options={
                'verbose_name': 'Request Session',
                'verbose_name_plural': 'Request Session List',
            },
        ),
    ]
