# Generated by Django 4.2 on 2023-04-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='language_filter',
            field=models.CharField(choices=[('id', 'Indonesia'), ('en', 'English')], default='id', max_length=4, verbose_name='Language Filter'),
        ),
    ]
